# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Publish to npm
on: { release: { types: [published] }, workflow_dispatch: null }
permissions: { contents: read, id-token: write }

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: { name: npm, url: "${{ steps.version.outputs.npm_url }}" }
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v7
        with: { node-version: latest, registry-url: https://registry.npmjs.org }
      - name: Install npm 11
        run: npm i -g npm@11
      - run: bun install

      # Stamp release version from the git tag into package.json
      - name: Set package version from tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: bun pm version from-git --allow-same-version --no-git-tag-version

      - run: bun build.ts
      - name: Set environment url
        id: version
        run: |
          name="$(jq -r .name package.json)"; echo "name=${name}" >> "${GITHUB_ENV}"
          version="$(jq -r .version package.json)"; echo "version=${version}" >> "${GITHUB_ENV}"
          echo "npm_url=https://npm.im/package/${name}/v/${version}" >> "${GITHUB_OUTPUT}"
          tarball="${name}-${version}.tgz"; echo "tarball=${tarball}" >> "${GITHUB_ENV}"
      - name: Pack tarball
        run: bun pm pack --filename "${tarball}"
      - name: Verify packed artifact installs
        run: |
          TMP_DIR=$(mktemp -d)
          npm install --prefix "$TMP_DIR" "./${tarball}"
          rm -rf "$TMP_DIR"
      - run: npm publish --provenance --access public "${tarball}"
